version: "2"
services:
  worker:
    build: ./worker
    image: worker
    links:
      - redis
  web:
    build: ./web/client
    image: web
    ports:
      - 9000:9000
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6380:6379
