version: "2"
services:
  worker:
    build: ./worker
    image: worker
    links:
      - redis
  web:
    build: ./web/client
    image: web
    links:
     - redis
    ports:
      - 9000:9000
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
